# Generated by Django 5.2.9 on 2026-01-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_orderstatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
    ]
